version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'notification-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/notification-db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"