version: '3.3'

services:
  db:
    image: mysql:5.7
    command: [--ignore-db-dir=lost+found]
    environment:
      MYSQL_DATABASE: 'notification-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - notification-db:/var/lib/db/data
    ports:
      - '3306:3306'

volumes:
  notification-db: